server:
  port: 20000                    #服务端口号
spring:
  application:
    name: config-server        #服务名称
  cloud:
    config:
      #profile: dev
      label: master          #配置仓库的分支
      server:
        git:
          uri: https://gitee.com/timer-man/gm-config # 配置git仓库地址
          #search-paths:      #配置仓库路径
          username: gmdeng  #访问git仓库的用户名
          password: pwd709394  #访问git仓库的用户名